# Generated by Django 3.0.7 on 2020-06-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_cheese_county_of_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='county_of_origin',
            new_name='country_of_origin',
        ),
    ]
